version: '3'

services:
    db:
        restart: always
        image: postgres:13.3-alpine
        volumes:
            - ${POSTGRESQL_PATH}
        environment:
            - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
        ports:
            - ${POSTGRESQL_PORT}:${POSTGRESQL_PORT}

    golang-web-app:
        build: ./
        command: bin/./main
        ports:
            - ${PORT}:${PORT}
        depends_on:
            - db
        environment:
            - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
            - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
            - POSTGRESQL_HOST=${POSTGRESQL_HOST}
            - POSTGRESQL_PORT=${POSTGRESQL_PORT}
            - POSTGRESQL_DB_NAME=${POSTGRESQL_DB_NAME}
